name: Lock Branch on Monday Night

on:
  schedule:
    - cron: '*/5 * * * *' # Every Monday at 00:00 UTC

jobs:
  lock-branch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lock Branch
        run: |
          BRANCH_NAME="lock_branch" # Replace with your branch name
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/branches/$BRANCH_NAME/protection"
          
          # Lock the branch using GitHub API
          curl -X PUT -H "Authorization: token ${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github.v3+json" $URL -d '{"lock_branch": true}'
