name: Create Tag using workflow

on:
  schedule:
    - cron: '*/5 * * * *' # Every Monday at 00:00 UTC

jobs:
  lock-branch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Set Dist Version
        run: |
          BUILD_VERSION="$(date %Y-%m-%d)"
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
      - name: Create Tag
        uses: actions/github-script@v6
        with:
          script: |
            const {BUILD_VERSION} = process.env          
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${BUILD_VERSION}`,
                sha: context.sha
            })
